In [31]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

#Getting the HTML

url = 'https://www.worldometers.info/world-population/'

page= requests.get(url)

soup = BeautifulSoup(page.text, 'lxml')

soup


table= soup.find('table', {'class': 'table table-striped table-bordered table-hover table-condensed table-list'})


headers = []

for i in table.find_all('th'):
    title = i.text.strip()
    headers.append(title)
    
df = pd.DataFrame(columns = headers)

for row in table.find_all('tr')[1:]:
    data = row.find_all('td')
    row_data = [td.text.strip() for td in data]
    length = len(df)
    df.loc[length] = row_data

df

,Year (July 1),Population,Yearly % Change,Yearly Change,Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population
0,2020,"7,794,798,739",1.05 %,"81,330,639",30.9,2.47,52,56.2 %,"4,378,993,944"
1,2019,"7,713,468,100",1.08 %,"82,377,060",29.8,2.51,52,55.7 %,"4,299,438,618"
2,2018,"7,631,091,040",1.10 %,"83,232,115",29.8,2.51,51,55.3 %,"4,219,817,318"
3,2017,"7,547,858,925",1.12 %,"83,836,876",29.8,2.51,51,54.9 %,"4,140,188,594"
4,2016,"7,464,022,049",1.14 %,"84,224,910",29.8,2.51,50,54.4 %,"4,060,652,683"
5,2015,"7,379,797,139",1.19 %,"84,594,707",30,2.52,50,54.0 %,"3,981,497,663"
6,2010,"6,956,823,603",1.24 %,"82,983,315",28,2.58,47,51.7 %,"3,594,868,146"
7,2005,"6,541,907,027",1.26 %,"79,682,641",27,2.65,44,49.2 %,"3,215,905,863"
8,2000,"6,143,493,823",1.35 %,"79,856,169",26,2.78,41,46.7 %,"2,868,307,513"
9,1995,"5,744,212,979",1.52 %,"83,396,384",25,3.01,39,44.8 %,"2,575,505,235"
10,1990,"5,327,231,061",1.81 %,"91,261,864",24,3.44,36,43.0 %,"2,290,228,096"
11,1985,"4,870,921,740",1.79 %,"82,583,645",23,3.59,33,41.2 %,"2,007,939,063"
12,1980,"4,458,003,514",1.79 %,"75,704,582",23,3.86,30,39.3 %,"1,754,201,029"
13,1975,"4,079,480,606",1.97 %,"75,808,712",22,4.47,27,37.7 %,"1,538,624,994"
14,1970,"3,700,437,046",2.07 %,"72,170,690",22,4.93,25,36.6 %,"1,354,215,496"
15,1965,"3,339,583,597",1.93 %,"60,926,770",22,5.02,22,N.A.,N.A.
16,1960,"3,034,949,748",1.82 %,"52,385,962",23,4.90,20,33.7 %,"1,023,845,517"
17,1955,"2,773,019,936",1.80 %,"47,317,757",23,4.97,19,N.A.,N.A.